services:
  audio-api:
    container_name: audio-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8468:3000"
    volumes:
      - ./audio:/usr/src/app/audio
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/audio
      - JWT_SECRET=secret
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
